openapi: 3.0.1
info:
  title: liangyuanguo
  description: ''
  version: 1.0.0
tags: []
paths:
  /blobs/1931607228851163136:
    get:
      summary: GetBlob
      deprecated: false
      description: ''
      tags: []
      parameters: []
      responses:
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
          headers: {}
      security: []
    post:
      summary: UploadBlob
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
            example: file://C:\Users\russionbear\Documents\GitHub\aw\blob\README.md
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  path:
                    type: string
                  size:
                    type: integer
                required:
                  - id
                  - name
                  - path
                  - size
          headers: {}
      security: []
    put:
      summary: PutBlob
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            example:
              name: name2
              desc: hihi
              contentType: application/octet-stream
              categories: 4v4
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /blobs/:
    get:
      summary: QueryBlob
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: q[categories]
          in: query
          description: ''
          required: false
          example: kw=4v4&
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        size:
                          type: integer
                        path:
                          type: string
                        uploadTime:
                          type: string
                        md5:
                          type: string
                        contentType:
                          type: string
                required:
                  - data
          headers: {}
      security: []
  /blobs/1931265153181945856.txt:
    delete:
      summary: DeleteBlob
      deprecated: false
      description: ''
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /static/1931262966640939008.txt:
    get:
      summary: GetStatic
      deprecated: false
      description: ''
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes: {}
servers:
  - url: http://localhost:8080/api
    description: 开发环境
security: []
